version: "3.4"

services:
  database:
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=somerootpass
        - MYSQL_PASSWORD=somepass
        - MYSQL_DATABASE=tracker_db
        - MYSQL_USER=someuser
  web:
    build: .
    ports:
        - 8080:80